### ISSUE TITLE
Stars are shinning one pixel off

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#100]
The stars are shinning correcly in the intro, but during the game they seem to be one pixel off. It is even visible in the original screenshot from the README:

https://camo.githubusercontent.com/3aebad4e63ca1703c1cebfe8e992874c570fcda6/68747470733a2f2f692e696d6775722e636f6d2f456e37354d7a782e706e67

**Comment by neuromancer** [comment]
Fixed ! (this was driving me crazy :scream: )

**Comment by scemino** [comment]
> Fixed ! (this was driving me crazy 😱 )

Sorry, I should have fixed it earlier, I hope your health is better now 😉
