### ISSUE TITLE
Selection of dialog choices is difficult

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#101]
The pointer seems to only point using the lower part of it:

![pointer](https://user-images.githubusercontent.com/110782/74877030-848d7a00-5343-11ea-8f07-1951ea897322.png)

I think it should be the center of it.

**Comment by scemino** [comment]
Yeah I have been to lazy to fix it yet 😁

**Comment by Mac1512** [comment]
I thought that these dialogues were not yet implemented, from what I see, I was wrong and they fail in windows.

When I give him talk to Willie, or even look at Willie, as well as when the sisters doves appear. At the moment in which the dialogues should appear, the program closes immediately.

The only thing I have seen in the log is this:

**[2020-02-20 03:33:42.566] [log] [error] Sorry, an error occurred: This is not an hashtable**

**Comment by neuromancer** [comment]
It works!
