### ISSUE TITLE
When you try to press escape during the intro, engge should show a "prohibition symbol" on the upper left corner

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#104]
This is from the original game:
![Captura de pantalla de 2020-02-21 16-44-09](https://user-images.githubusercontent.com/110782/75066352-6e112b00-54c9-11ea-875c-7e198c48672a.png)

**Comment by scemino** [comment]
Yes, I know, but I didn't find yet where this resource is located, in which file 😞

**Comment by Mac1512** [comment]
That resource is found in the file "GameSheet.png"

**Comment by scemino** [comment]
> That resource is found in the file "GameSheet.png"
Where exactly I don't see it.

**Comment by Mac1512** [comment]
I give you a screenshot, where I put an arrow and a circle around the symbol

![prohibition](https://user-images.githubusercontent.com/2179224/75098410-23b9a800-55b6-11ea-8b37-55a3a7ebf232.PNG)

**Comment by scemino** [comment]
Thank you, I was working on a older version, and it didn't exist yet as you can see:

<img width="654" alt="Capture d’écran 2020-02-22 à 21 07 54" src="https://user-images.githubusercontent.com/643384/75098515-7b0c4800-55b7-11ea-8dac-ddc211fb9014.png">
