### ISSUE TITLE
The mouse cursor of the game (Cross) disappears when the dialogue with the sisters "Pigeon Brothers" begins

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#106]
The mouse cursor of the game (Cross) disappears when the dialogue with the sisters "Pigeond Brothers" begins

At that moment only the windows cursor "the arrow" remains, although I can activate it again from the debug menu, to select the dialog options I can continue with the windows cursor. When the dialogue is over, the game cursor automatically reappears.

![pigeon](https://user-images.githubusercontent.com/2179224/75187176-d40be580-5749-11ea-8cd4-3af3385756d9.PNG)

**Comment by scemino** [comment]
Maybe I can always activate the cursor when the dialog choices are displayed
