### ISSUE TITLE
The dialogs are not visible

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#110]
Following the arrangements that you have made in the last commits, the text of the dialogs is not shown on the screen, but if you click with the mouse in the place where the text should be, the selection works correctly.

**Comment by scemino** [comment]
Can you specify in which dialog ? Who talk to who and where.
Do you have a screenshot ?
Thank you.

**Comment by Mac1512** [comment]
It happens to me in all the dialogues, I've tried it with willie, pigeon brothers, sheriff and the same result

I pass you a link to YouTube where I have uploaded a video of the dialogue with Willie, there you can also appreciate how it detects the actor "Willie", showing the text Talk to "Talk", or the object "WillieObject" showing the text look at " Look "as I had mentioned in another issue.

Link to the video:

https://youtu.be/nxxvDBZttzQ
