### ISSUE TITLE
Boris can escape of the screen

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#111]
In the first screen, before opening the gate, Boris can be off-screen if you click on the left side as it shows the screenshot:

![out](https://user-images.githubusercontent.com/110782/76169429-c47f9a00-6156-11ea-9688-a294d7ce72cd.png)

Click on any other place will bring him back.

**Comment by scemino** [comment]
I can do the same with the original
<img width="1348" alt="boris-invisible" src="https://user-images.githubusercontent.com/643384/76169784-f0614680-617b-11ea-8296-e3083a9b3334.png">

**Comment by neuromancer** [comment]
Interesting!, well, let's close this bug (and tell Ron Gilbert about it!).
