### ISSUE TITLE
Willie doesn't usually fall asleep when dialog options have been selected.

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#114]
When the dialogue between Willie and Boris begins, in the Bridge Room, as dialogue options are selected, Willie should fall asleep, but he usually stays with his eyes open.

The few times he appears with his eyes closed, the following text never appears:

24839 {asleep} * snore *

And the sound is not heard either.

**Comment by Mac1512** [comment]
In windows, willie's head blinks when he sleeps and he's snoring

**Comment by scemino** [comment]
Yes, you're right, I was aware of this bug, this is why I added a "head
index" in the debug tools, because when Willie is snoring, his lips are
moving (the head index changes) but it uses a head index which is not
possible "head2", this why his head is invisible sometimes.

**Comment by Mac1512** [comment]
Ok, now I understand why this commit head index "Add head index in debug tools"
