### ISSUE TITLE
Failures observed in script execution in dialogue between Ray and Reyes

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#123]
Failures observed in script execution in dialogue between Ray and Reyes

When Ray establishes dialogue with Reyes, an error appears in the execution of the script code when starting and ending the dialogue.

When Reyes establishes dialogue with Ray, only an error appears in the scrip code at the end of the dialogue. This error is the same one that appears when the Ray dialog ends.

**Failure occurred when starting the dialogue, actor Ray:**

![Dialog strat Ray](https://user-images.githubusercontent.com/2179224/78834606-26018580-79ef-11ea-8a52-fefeae1065ae.PNG)

**Failure at the end of the dialogue both actors:**

![End Ray and Reyes](https://user-images.githubusercontent.com/2179224/78834661-39145580-79ef-11ea-910f-5cca2acf5f36.PNG)

Although the screenshots correspond to a much earlier commit, this also happens in the last one.

I have also observed other errors that I had already corrected, which have reappeared as a result of the changes you are making in the code, so I will wait a few days before notifying you, in case future commits are solved again.

This is only tested on windows

**Comment by scemino** [comment]
It should be fixed by eb925952af24adb0c97147ca1f7f41ca93e7b9da

**Comment by scemino** [comment]
I plan a v0.6.0 soon. In this release I tried to fix a lot of script errors and memory leaks, this should be more stable. @Mac1512 can you confirm that you have no script error or crash ? Thank you

**Comment by Mac1512** [comment]
Leave me a few days to try and I will confirm it

**Comment by Mac1512** [comment]
Hello, I am doing tests, and the last commit that works for me is the
following: *Add a console* (
https://github.com/scemino/engge/commit/000b18e62b96024fca2d20a59b2544375fd08454
).

There is an error from this commit:* Add print and actors commands to
console* (
https://github.com/scemino/engge/commit/32409557a2f65bac5e9f99924e94c55356846aee)
that throws me an exception and I haven't seen what causes it yet.

I'm going to test the last one that works for me, in case I see any error,
but of course, it would be convenient to solve from *Add print and actors
commands to console*, and keep testing from there before releasing a
version 0.6.0.

Too bad I couldn't try before ...

**Comment by scemino** [comment]
> There is an error from this commit:* Add print and actors commands to console* ( [3240955](https://github.com/scemino/engge/commit/32409557a2f65bac5e9f99924e94c55356846aee)) that throws me an exception and I haven't seen what causes it yet.

What kind of exception, what did you do before it throws the exception ? Can you tell me more please ? Thanks for your tests.

**Comment by Mac1512** [comment]
I'm going to try now ... I'll give you an answer shortly

**Comment by Mac1512** [comment]
> 
> 
> > There is an error from this commit:* Add print and actors commands to console* ( [3240955](https://github.com/scemino/engge/commit/32409557a2f65bac5e9f99924e94c55356846aee)) that throws me an exception and I haven't seen what causes it yet.
> 
> ~What kind of exception, what did you do before it throws the exception ? Can you tell me more please ?~ Thanks for your tests.
> Do you have a StackOverflowException ? I think I found the problem ;)
> Can you check this commit [c093504](https://github.com/scemino/engge/commit/c093504c9b08471a5a13841af92218a2bf90a476) please ?

You were right, that was the problem ... **now it works :)**

I should have clarified better the type of exception that was happening and where the failure was ...

**Comment by scemino** [comment]
> > > There is an error from this commit:* Add print and actors commands to console* ( [3240955](https://github.com/scemino/engge/commit/32409557a2f65bac5e9f99924e94c55356846aee)) that throws me an exception and I haven't seen what causes it yet.
> > 
> > 
> > ~What kind of exception, what did you do before it throws the exception ? Can you tell me more please ?~ Thanks for your tests.
> > Do you have a StackOverflowException ? I think I found the problem ;)
> > Can you check this commit [c093504](https://github.com/scemino/engge/commit/c093504c9b08471a5a13841af92218a2bf90a476) please ?
> 
> You were right, that was the problem ... **now it works :)**
> 
> I should have clarified better the type of exception that was happening and where the failure was ...

No problem, it was quite easy ;)
Thanks for your quick feedback.
Don't hesitate to create an issue, if you find anything.
If you find a crash, I will postpone the release, if not then I will release the 0.6.0 version.
