### ISSUE TITLE
Hide parenthesis in dialogs

### ISSUE THREAD

**Issue by scemino** [scemino/engge#14]
**Describe the bug**
Hide words in parenthesis in dialogs.

**To Reproduce**
Type this test.nut:
```
include("Defines.nut")
include("Boot.nut")

inputOn()
inputVerbs(ON)
selectActor(ray)
enterRoomFromDoor(highwayBridgeDoor)
sayLine("@30344")
```
**Expected behavior**
Actor should say "It's already open.", not "(neutral)It's already open."

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Mojave 10.14.4

**Comment by neuromancer** [comment]
I wonder if the text in parenthesis is used somehow (for instance to change the face of the talking character) ? If it is a "bonus" feature, you could give the user the option to hide it or not.

**Comment by scemino** [comment]
I think these parenthesis are used during voice recordings (male, female, neutral, sarcastic, etc.), but as you can see in Thimbleweed Park, these parenthesis are removed.
