### ISSUE TITLE
Impossible to leave the coroner's room

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#209]
**Describe the bug**
Impossible to leave the coroner's room

**To Reproduce**

In Part 2: After talking to the Sheriff, Ray and Reyes are going to talk to the coroner, after talking to him, They can't leave the room, this message appears in the log:

**[2020-06-18 02: 56: 59.156] [log] [trace] can't find verbCantReach function**

The same thing happens in Part 1, when Boris tries to talk to Willie. The same message appears in the log. The rest of the verbs do nothing when used in Willie.

**Expected behavior**

To be able to leave the room

**Screenshots**

None

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Version 10

**Additional context**

Tested on commit: (https://github.com/scemino/engge/commit/dc22e2307408db0dc3d27c9c6432be41ceab9555)

**Comment by scemino** [comment]
Yeah, sorry about that.
I'm working on it, I try more generally to fix verbs bugs:
* Boris talk to Willie
* Boris use the rock on lamp
* Reyes talk to Sandy
* Ransome should be able to push the mime
* Reyes talk to Ray
* Reyes give the Polaroid film to ray
* Ransome give the theremin record to someone else
* And more
