### ISSUE TITLE
GGPack File Version

### ISSUE THREAD

**Issue by mbone** [scemino/engge#21]
I have tested windows version 938, 958 & 957 and cannot get them to recognise,

 Which version is compatible?

**Comment by scemino** [comment]
I'm working essentially with the EPIC Games version 1420.955.
But I own also the GOG version 1421.958, so I can try to fix this version, for the other versions, it will be hard for me to fix them without testing.

**Comment by mbone** [comment]
957 & 958 gog versions will not pass the 0x04030201 stage ("This version of package is not supported (yet?)"); which is strange as they open up in the thimbleweed park explorer program fine.

but the 938 version will dump the file list but has some corrupt entries, I can email a screenshot of it if you wish. then crashes later on in the program so I don't think its dumping the files correctly yet. It maybe down to the visual studio compiler but i'm just not sure.

**Comment by scemino** [comment]
Maybe this is due to endianness, because version 958 works on my Mac.

**Comment by mbone** [comment]
after some more testing. I found that when decodeUnbreakableXor(&buf[0], dataSize); in the method loop is called, the data in buf0 changes, which is strange as I would of thought this should always be the same value. 

if I switch the  0x6d : 0xad values round it sort of decodes the file.

something very strange with compiling this on a windows machine

**Comment by mbone** [comment]
it turns out you need to add std::ios::binary to the open statement in GGpack.cpp.

void GGPack::open(const std::string &path) 
{ 
    _input.open(path, std::ios::binary); 
    readPack(); 
 }

**Comment by scemino** [comment]
I reproduced it, you're right, it seems better with this.
Don't hesitate to send a pull request to fix this.
Thank you.
