### ISSUE TITLE
Talking can stop the game

### ISSUE THREAD

**Issue by scemino** [scemino/engge#234]
**Describe the bug**
When you talk to someone if there is no lip file, the game stops.

**To Reproduce**
1. Use Ransome the first time
2. Click on the hint flyer
3. Ransome should say `It says, "Need help playing Thimbleweed Park?"`

**Expected behavior**
The engine is expecting a lip file corresponding to the text, but sometimes there is no lip file associated, in this example it's normal because we don't see Ransome.
The game should ignore and not crash 😉

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: BigSur 11.1

**Comment by Mac1512** [comment]
I have compiled the commit: (https://github.com/scemino/engge/commit/17c5081edc596c05ae702ce0be8eb6a3124e3c8f)

In **debug mode**, it still crashes when Boris speaks, I think there is still a problem in some "Lip" file.

It has thrown me an exception:

![debug_fail_river](https://user-images.githubusercontent.com/2179224/107132342-569b9f80-68de-11eb-8918-bd22869fa30a.PNG)

![debug_fail_river 2](https://user-images.githubusercontent.com/2179224/107132345-5b605380-68de-11eb-81b6-29b26f442a1e.PNG)


In **Release mode**, I have not tried, but I have tried the version **0.7.1 Beta** that you have released and being in release mode, in that part it does not fail. So, just throw the exception in Debug mode.
