### ISSUE TITLE
Lip keeps failing when Boris speaks

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#240]
I have compiled the commit: (https://github.com/scemino/engge/commit/17c5081edc596c05ae702ce0be8eb6a3124e3c8f)

In **debug mode**, it still crashes when Boris speaks, I think there is still a problem in some "Lip" file.

It has thrown me an exception:

![debug_fail_river](https://user-images.githubusercontent.com/2179224/107132342-569b9f80-68de-11eb-8918-bd22869fa30a.PNG)

![debug_fail_river 2](https://user-images.githubusercontent.com/2179224/107132345-5b605380-68de-11eb-81b6-29b26f442a1e.PNG)

In **Release mode**, I have not tried, but I have tried the version **0.7.1 Beta** that you have released and being in release mode, in that part it does not fail. So, just throw the exception in Debug mode.

_Originally posted by @Mac1512 in https://github.com/scemino/engge/issues/234#issuecomment-774561684_

**Comment by scemino** [comment]
Thank you. I know that vectors access are checked in Windows in debug but not with Linux or macOS.
If I change the code intead of using `[]` I use the method `at` then I have same issue.
I think Windows is better with this, because it detects out of bounds access.
It will be fixed soon.

**Comment by Mac1512** [comment]
You're welcome, I already assumed that Linux and Mac were more permissive, because otherwise I would give you the same failures as me :)

With this change you've made, Visual Studio doesn't give me the exception, though when Boris says the last sentence, before I can manipulate it. This phrase is not displayed on the screen, although if it is heard, it takes a while for the mouse cross to appear so that you can start playing.

It also becomes slow when you want to save or load a game, you have to wait a while for it to react.

Nothing else I can, I will compile in release mode and test if it does the same. Now I'm running late and it takes me a while to add the missing libraries to compile. And I'll also do a clean compilation in debug mode just in case.

I have also opened two issues in engge Framework. Some bug I have already corrected, however, in case you want to take a look, they are the following:

https://github.com/scemino/EnggeFramework/issues/1

https://github.com/scemino/EnggeFramework/issues/2
