### ISSUE TITLE
Building issues in Windows

### ISSUE THREAD

**Issue by scemino** [scemino/engge#250]
@Mac1512 has several issues to build `engge` in Windows:

> 
> 
> OK thank you for the clarifications.
> I'll have a look of the modifications and try to understand what's going on.
> I'll try to revert the modifications to see if it's faster on my computer.
>

Thanks for going back and trying, I'll do the same ...
 
>
>
> Wow, you seem to make a lot of modifications to test my commits, I'll try to create a page about vcpkg as soon as possible.
>

Also thank you scemino for the speed in creating a page with the building instructions.

With vcpkg it works great :)

However, I have to create an issue, since it fails with the instructions as you have put them. I will put it as I have done it, so that there is no problem in windows. In case you estimate to change it 

**Edited:**

I have changed a couple of things to make it work, since: 

if i do this

**git clone https://github.com/Microsoft/vcpkg.git**

when I run this line:

**vcpkg install sfml:x64-windows freetype:x64-windows glew:x64-windows sdl2:x64-windows glm:x64-windows**

will fail in openalsoft, stopping the process: 

![fallo openalsoft](https://user-images.githubusercontent.com/2179224/107588098-50b9fd00-6c03-11eb-9256-406a11000c72.PNG)

Then, instead of executing the git clone command, I download the latest stable version of vcpkg, in the address bar of the internet browser I put the following: 

**https://github.com/microsoft/vcpkg/archive/2020.11-1.zip**

then I change this:

**cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install**

For this: 

**cd vcpkg
bootstrap-vcpkg.bat
vcpkg integrate install**

I run this: 

**vcpkg install sfml:x64-windows freetype:x64-windows glew:x64-windows sdl2:x64-windows glm:x64-windows**

Clones the repo:

**git clone https://github.com/scemino/engge.git**

and clones the repo:

**git clone https://github.com/scemino/EnggeFramework.git**

I copy the content of the EnggeFramework repository to **engge/extlibs/ngf**

and I do the rest of the instructions.

Tomorrow I will detail it a little better, in case someone who uses windows wants to compile it.

_Originally posted by @Mac1512 in https://github.com/scemino/engge/issues/242#issuecomment-777116391_

**Comment by scemino** [comment]
I see that you have this error:
> please ensure you're using the latest portfiles with .\vcpkg update

I had several issues myself to build on Windows, I remember several things in Visual studio installer (or go to the menu `Tools > Get tools and Features...` in Visual Studio)
* select the `Language packs` tab, and be sure you have the English version installed
* select the `Individual components` tab, you need to check
  - [x] Windows 10 SDK kit
  - [x] CMake tools for Windows
  - [x] MSVC v142 - VS2019 C++ x64/x86 Build tools (latest version)

After this, `vcpkg` should work correctly, if not can you make a screenshot of your `Individual components` options.

You don't need to do this:
> and clones the repo:
>
> git clone https://github.com/scemino/EnggeFramework.git
>
> I copy the content of the EnggeFramework repository to engge/extlibs/ngf

I made a mistake in the [building page](https://github.com/scemino/engge/wiki/Build-instructions), I forgot the `--recurse-submodules` option.
You can type this:
`git clone --recurse-submodules https://github.com/scemino/engge.git`
And it will clone the repo and also the submodules.

**Comment by Mac1512** [comment]
Thank you very much for the indications, now it has worked perfectly :)
