### ISSUE TITLE
Feature request: Release early, release often

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#49]
I'm following other game re-implementation like [OpenNitemare3D](https://github.com/BBQGiraffe/OpenNitemare3D). The developer produces [releases often](https://github.com/BBQGiraffe/OpenNitemare3D/releases), basically every time a new feature is implemented and needs testing. I wonder if the same approach could be followed during the development of engge.

**Comment by scemino** [comment]
Yes I was thinking of modifying travis configuration to create pre releases of engge. I will try to do this, when I can.

**Comment by scemino** [comment]
Done, now I can release a new version whenever I create a tag, I provide a zip file for each OS: Linux, MacOS and Windows.

**Comment by neuromancer** [comment]
Neat!, don't forget to include a short description of what to expect in each release. It helps potential users to know what to expect and report useful issues!

**Comment by scemino** [comment]
Yes, but I didn't know what to say in this release because it's still unstable and there is a lot to do.

**Comment by scemino** [comment]
@neuromancer can you confirm that it works for you? Thank you

**Comment by neuromancer** [comment]
Do you mean [this release](https://github.com/scemino/engge/releases/tag/v0.1.0-alpha) ?

**Comment by scemino** [comment]
Yes, I only released 1 version, but I plan to release another one soon, but I'm not sure it works on Linux and Windows.

**Comment by neuromancer** [comment]
Fair enough. Let me test it.

**Comment by neuromancer** [comment]
The Linux binary looks good, but it needs the `libImGui-SFML.so` to run in my system. Other dependencies (e.g SFML or libIm) are usually available to install in several different Linux distros (e.g. ArchLinux). I recommend to ship this library with the binary.

Btw, I can't test the windows binary.

**Comment by scemino** [comment]
Thank you @neuromancer  for your feedback, I reopen this ticket and I plan to fix (I hope it will be easy).

**Comment by neuromancer** [comment]
I think you should ship all the compiled .so and let the users to test it. There is no way to have an universal executable in Linux (unless you have an approach like flatpak or snap)

**Comment by scemino** [comment]
If you know how to do it or if you have an example you're welcome, because I'm not a cmake expert, and I lose a lot of time trying to find a good example how to do it.

**Comment by neuromancer** [comment]
Sure. I can handle this. When you want to do the new release?

**Comment by scemino** [comment]
There is no rush, you know I have no boss, I can release whenever I want 😉, so I can wait until you have time to look at this. 
Thanks for your help @neuromancer

**Comment by neuromancer** [comment]
I will take a look this during the weekend. Sorry for the delay (Github should have an feature to remind you about this kind of task!)

**Comment by scemino** [comment]
Cool, because a lot of fixes have been made since last time.
Thank you.

**Comment by scemino** [comment]
Any update @neuromancer ?

**Comment by neuromancer** [comment]
I was experimenting with cmake, but the easiest way to release a "portable binary" for Linux is to compile it as usual (in the CI servers) and distribute certain libraries. The result will be a dynamically linked binary, including these libraries:
```
        ...
	libImGui-SFML.so (0x00007f6bcbde9000)
	libsfml-graphics.so.2.5 => /usr/lib/libsfml-graphics.so.2.5 (0x00007f6bcbd3e000)
	libsfml-audio.so.2.5 => /usr/lib/libsfml-audio.so.2.5 (0x00007f6bcbd22000)
	libsfml-window.so.2.5 => /usr/lib/libsfml-window.so.2.5 (0x00007f6bcbcf7000)
	libsfml-system.so.2.5 => /usr/lib/libsfml-system.so.2.5 (0x00007f6bcbce9000 
        ...
```
libsfml and libImGui-SFML are not usually included in the repositories of the Linux distros (or sometimes the versions are quite old). A specific .sh is needed to run the game, setting the LD_LIBRARY_PATH to point to a directory containing the precompiled libraries. 

What do you think?

**Comment by scemino** [comment]
I'm not an expert of Linux, you know better than me. 
The only thing is I'm not fond of setting an environment variable and having a script to run the game.
Do you know other SFML game with a setup which can help us ?
Anyway thank you @neuromancer

**Comment by neuromancer** [comment]
I can setup the release if you want. As a alternative to use `LD_LIBRARY_PATH`, you can use `patch` like this:

```
$ patchelf --remove-needed ./libImGui-SFML.so ./build/src/engge
$ patchelf --add-needed ./lib/libImGui-SFML.so ./build/src/engge
```

Then Linux will try to load `libImGui-SFML.so` in the `lib` directory.

**Comment by neuromancer** [comment]
Take a look to #83
