### ISSUE TITLE
Remove extlibs/*/Makefile and add them to .gitignore

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#5]
After compiling engge in Linux, a few `Makefiles` inside `extlibs/*` are listed as modified. It would be nice to remove them (since they are autogenerated) and add them into `.gitignore`.

**Comment by scemino** [comment]
You're right I made a mistake in the README you need to do this to compile:
```
mkdir build
cd build
cmake ..
cmake --build .
```
I will fix this

**Comment by neuromancer** [comment]
Great. Feel free to close (or modify) PR #7 when you change the README.
