### ISSUE TITLE
Actor text should be wrapped

### ISSUE THREAD

**Issue by scemino** [scemino/engge#51]

**Comment by neuromancer** [comment]
This is also an issue with notes:

![note](https://user-images.githubusercontent.com/110782/75787509-9872ac00-5d45-11ea-97ec-9fc6fadc36b1.png)

**Comment by neuromancer** [comment]
I think this fix caused this issue in the pause message:
![paused](https://user-images.githubusercontent.com/110782/76169308-a6656a00-6155-11ea-9458-80f3b5053489.png)

**Comment by scemino** [comment]
yes you're right @neuromancer, thank you.
I fixed it.

**Comment by neuromancer** [comment]
That's working, thanks! :smile:. However other menus are showing incorrectly (at least with my resolution/window size):

![sound](https://user-images.githubusercontent.com/110782/76169680-73bd7080-6159-11ea-89ba-3d0c290ce68a.png)

**Comment by Mac1512** [comment]
> That's working, thanks! 😄. However other menus are showing incorrectly (at least with my resolution/window size):

It happens to me too, the menu texts also appear at the wrong height

**Comment by scemino** [comment]
You're right, it should be fixed in 600901a519f8c780e7a08fe73fd6e26ee71be556
