### ISSUE TITLE
Setup CI tests to avoid crossplatform issues

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#6]
It would be nice to setup some CI tests to detect crossplaform issues when compiling and running engge. It is worth to mention that [travis](travis-ci.com) is free for open-source repositories and has support for Linux and OSX.

**Comment by scemino** [comment]
This is not so easy as it seems, actually I have some issues with C++17 and travis, you can have a look here: https://travis-ci.org/scemino/engge

**Comment by neuromancer** [comment]
Do you really need to install it? should't be enough to compile it and test it in-place?

**Comment by scemino** [comment]
Look at the history, I tried a lot of solutions.

**Comment by neuromancer** [comment]
Sorry I can't help. I don't have experience with OSX. A workaround is to enable the CI tests only in Linux.

**Comment by scemino** [comment]
I tried to build on Linux as you can see in [build #26](https://travis-ci.org/scemino/engge/builds/510648334)
```
Scanning dependencies of target engge
[ 27%] Building CXX object CMakeFiles/engge.dir/src/Game.cpp.o
g++: error: unrecognized command line option ‘-std=c++17’
make[2]: *** [CMakeFiles/engge.dir/src/Game.cpp.o] Error 1
make[1]: *** [CMakeFiles/engge.dir/all] Error 2
make: *** [all] Error 2
The command "cmake --build . --config Release" exited with 2.
```

**Comment by neuromancer** [comment]
The gcc/g++ version is very old. Try again upgrading to gcc/g++ 8. Use this ppa:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial

**Comment by neuromancer** [comment]
Can you add the .travis file to `master`? I should be able to fix this..

**Comment by scemino** [comment]
Thank you for your help, now the build fails later... but maybe I can fix this.
