### ISSUE TITLE
Fails to execute a second cutscene

### ISSUE THREAD

**Issue by Mac1512** [scemino/engge#65]
If the engine runs a single cutscene it works almost correctly, but when you run a second one, the program closes immediately.

I say almost correctly, because for example, if you enter the Bridge.bnut room, starting from the beginning, that is, setting the local variable doStart to true, in the file test.nut. When the first cutscene is almost over, Boris does not say the last sentence.

This is due to executing the function a second time:

static SQInteger cutscene (HSQUIRRELVM v)

although in the file (Cutscene.cpp) the constructor of the following class runs correctly:

Cutscene :: Cutscene (Engine & engine, HSQUIRRELVM v, HSQOBJECT thread, HSQOBJECT closureObj, HSQOBJECT closureCutsceneOverrideObj, HSQOBJECT envObj)
    : _engine (engine), _v (v), _thread (thread), _state (0), _closureObj (closureObj), _closureCutsceneOverrideObj (closureCutsceneOverrideObj), _envObj (envObj)
{...}

on the contrary, the following function does not execute, and the cutscene does not start:

void Cutscene :: operator () (const sf :: Time & elapsed)

To solve it, I have changed, in the file _GeneralPack.h, in the function:

static SQInteger cutscene (HSQUIRRELVM v)

I have commented the following code:

/ * auto pThread = ScriptEngine :: getThreadFromVm (v);
pThread-> suspend ();
return SQ_SUSPEND_FLAG; * /

and I have put the following:

return sq_suspendvm (v);

To make this change (return sq_suspendvm (v);), I relied on its release version code. This is applicable to the current version of the repository.

Surely there is a better way to achieve the right result, but this works for me for now. It is only one way to do it, surely you manage to do it in a much better way.

With this change, the cutscenes are executed correctly. In the example I set out above, boris says the last sentence.

Greetings.

**Comment by scemino** [comment]
OK @Mac1512 can you try again please with the latest commit ed2624f?
Thank you for your issue.

**Comment by Mac1512** [comment]
Hello, this weekend I have been traveling.

With this commit
https://github.com/scemino/engge/commit/ed2624f42d4105c09d3504063e46f33b426f6c82
the second cutscene works correctly. Although I failed once the program
closed unexpectedly, once Title Cards 2 started, when Ray and Reyes first
appear running the game from the beginning. Although this is something I
should try in more detail. although I haven't had enough time yet. In this
commit, the helperscreens do not display the backgroud, the backgroud being
blue. Anyway I will try since the last commit, since I see that you have
made several changes.

The last commit
https://github.com/scemino/engge/commit/fcd3f38190c16538359503a3aaa847bfcb7625b0,
although I have tried it above, it goes quite well in relation to cutscenes
and other bugs that you have corrected, although there are still bugs, for
example, when the stone is used on the sign, the sound of breaking the bulb
does not sound. And I also see that the two actors disappear, while they
are talking at the beginning of the title card 2.

----

Anyway I am going to comment on a series of bugs, which I have been
observing, generally in commits, although you may already know them.

1. When a new chapter (Title Cards) is started, the camera does not focus
and the title is not visible. This happens from the second chapter, since
it should take as a reference the last position of the camera, to solve it
you would have to implement that the camera is centered at 0, when it
starts.

2. Sometimes, when walking, take the wrong walkbox, that is when there are
two walkboxes at the scene. You should walk for one and if you select the
second walk for this, or maybe a mixture of both. but on the contrary,
sometimes he walks by the one who should not. for example, in title card 1,
that is to say at the beginning, you can get through the closed door.

3. The actor's lips do not move throughout the sentence.

4. When I change the language, I have only tried Spanish, the initial
images are not changed automatically, I know this is not implemented. But
what I do see is that when you hover your cursor over the inventory or
another object, an #M or #F appears after the text, and this in the release
version did not come out.

I hope to have more time from Wednesday to try and so I can tell you in
more detail.

regards

**Comment by scemino** [comment]
Thank you for your feedback, I created severals separated  issues: #70 #71 #72 #73 #74 it's easier for me to fix one bug at a time, so I split this issue in several.
Do you agree @Mac1512  if I close this one about the cutscene, it's fixed also for you ?
Your report is really welcome, great job !

**Comment by Mac1512** [comment]
Hello, first of all, thank you for your efforts.

I find it very successful to create different issues for each problem and thus address them separately. It's true, it's easier :)

I have seen that you have corrected:

1. Fix sound in animation does not work (https://github.com/scemino/engge/commit/c32b67b315ef2570ba1a2ef819457f897875a82c)

That affected, what I had told you, for example by breaking the lamp with the stone in the first chapter.

2. other than what I had told you about the camera in the title cards. You have corrected it in the last commit (https://github.com/scemino/engge/commit/21f9b6cac623e60980de493165307b499445d406).

I have tried it, and both the sound when breaking the lamp for example, as the reset of the camera both work correctly.

I think that at this point, you can terminate this issue, since the cutscenes are executed correctly.

regards

**Comment by scemino** [comment]
Great ! thank you.
