### ISSUE TITLE
Fix Windows compilation

### ISSUE THREAD

**Issue by scemino** [scemino/engge#87]
The Windows release version was incorrect.
This needs to be fixed.
We could provide a 32 and a 64 bits versions.

**Comment by neuromancer** [comment]
The linux binary should be easier to run now since it was compiled for Ubuntu 18.04. So, If you fix this, you could release version 0.2.1 instead of jumping to 0.3.0 (unless that version is closer than I expect.. :open_mouth: )

**Comment by scemino** [comment]
> The linux binary should be easier to run now since it was compiled for Ubuntu 18.04

By the way I tested it on my Ubuntu 19.10, it works like a charm, 👍 @neuromancer

> If you fix this, you could release version 0.2.1 instead of jumping to 0.3.0 (unless that version is closer than I expect.. 😮 )

Or I plan to fix it not so soon.
Actually @Mac1512 provided me a binary of engge for Windows, I tested it and I added the missing dependencies and I updated the zip in the release, so there is no rush to do it the right way 😉

**Comment by scemino** [comment]
I added this commit to add dependencies in the package: 78d5382be42a31cda327737108d6bbd9e6ad90c1
