### ISSUE TITLE
You can still switch to Boris after playing the first chapter

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#93]

**Comment by scemino** [comment]
Actually `actorSlotSelectable` is not called at the end of the first chapter.
Maybe if an actor is in room called `Void` we can consider this actor not selectable.
Do you agree ?

**Comment by neuromancer** [comment]
I'm not sure, but it looks like. When I try to switch to Boris after chapter 1, everything looks black. Perhaps he is in this special `Void` room?

**Comment by neuromancer** [comment]
It seems to work as expected now. Thanks!
