### ISSUE TITLE
Feature request: allow left-click to advance dialogue

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#95]
It seems to be available in the original game: https://steamcommunity.com/app/569860/discussions/0/133261124638040356/

**Comment by scemino** [comment]
OK I propose to support the same as the original game, you can add this to `Prefs.json`:
```
keySkipText: "."
rightClickSkipsDialog: 1
```
If you press the period or if you use right click, it skips the dialog.

**Comment by neuromancer** [comment]
Fair enough.
